/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/components/AddItem.vue')['default']
    AddItemForm: typeof import('./src/components/AddItemForm.vue')['default']
    EditItemForm: typeof import('./src/components/EditItemForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Items: typeof import('./src/components/Items.vue')['default']
    NewItem: typeof import('./src/components/NewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
